import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import MODULOSTAREAMODELAMIENTO.CConexion;

public class Asistencia_de_Alumnos extends javax.swing.JFrame {
  
// --- ESTO VA EN LISTA DE ALUMNOS (Formulario 2) ---

public void cargarAlumnosPorCurso(String cursoSeleccionado) {
    
    // 1. Conexión estándar
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblAlumnos.getModel();
    modelo.setRowCount(0);
    
    MODULOSTAREAMODELAMIENTO.CConexion conObj = new MODULOSTAREAMODELAMIENTO.CConexion();
    java.sql.Connection conect = conObj.establecerConexion();
    
    // 2. LA CONSULTA BLINDADA (Soluciona el problema de Quimica vs QUIMICA)
    // Usamos UPPER() para convertir todo a mayúsculas temporalmente al comparar
    String sql = "SELECT apellidos, nombres FROM lista_alumnos WHERE UPPER(curso) LIKE UPPER(?)";
    
    try {
        java.sql.PreparedStatement pst = conect.prepareStatement(sql);
        
        // Agregamos "%" para que funcione incluso si hay espacios invisibles
        pst.setString(1, "%" + cursoSeleccionado.trim() + "%");
        
        java.sql.ResultSet rs = pst.executeQuery();
        
        int contador = 1;
        while(rs.next()) {
            String apellidos = rs.getString("apellidos");
            String nombres = rs.getString("nombres");
            modelo.addRow(new Object[]{ contador, apellidos, nombres, false });
            contador++;
        }
        conect.close();
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

     // 1. Variable para guardar el ID que viene del formulario anterior
    int idPracticaActual = 0; 
    private PanelLienzoFirma lienzoFirma;
    
    public Asistencia_de_Alumnos() {
        initComponents();
        setLocationRelativeTo(null);
        
        // --- CÓDIGO CORREGIDO EN EL CONSTRUCTOR DE Asistencia_de_Alumnos ---

    // 1. Creamos el lienzo de dibujo
    lienzoFirma = new PanelLienzoFirma();

    // 2. ¡LA SOLUCIÓN!
    // Le decimos al nuevo lienzo: "Tu tamaño ideal debe ser el mismo tamaño
    // que el panel contenedor que Martin dibujó en el diseño".
    lienzoFirma.setPreferredSize(panelContenedorFirmaAsistencia.getPreferredSize());
    // Por seguridad, forzamos también el tamaño actual si ya estuviera calculado
    if (panelContenedorFirmaAsistencia.getWidth() > 0) {
       lienzoFirma.setSize(panelContenedorFirmaAsistencia.getSize());
    }


    // 3. Ahora sí lo agregamos al contenedor.
    // Usamos BorderLayout para que rellene todo el espacio disponible.
    panelContenedorFirmaAsistencia.setLayout(new java.awt.BorderLayout());
    panelContenedorFirmaAsistencia.add(lienzoFirma, java.awt.BorderLayout.CENTER);

    // 4. Forzamos a que el diseño se recalcule y se repinte
    panelContenedorFirmaAsistencia.revalidate();
    panelContenedorFirmaAsistencia.repaint();
    }


    // 2. Método para que el formulario anterior nos pase el ID
    public void setIdPractica(int id) {
        this.idPracticaActual = id;
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        btnExportarLista = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnRegresarLista = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        panelContenedorFirmaAsistencia = new javax.swing.JPanel();
        btnBorrarFirmaAsis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_uai123456789.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 160, 60));

        jPanel1.setBackground(new java.awt.Color(111, 172, 199));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTA DE ALUMNOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 24))); // NOI18N

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Apellidos", "Nombres", "Asistencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblAlumnos.setAutoscrolls(false);
        tblAlumnos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblAlumnosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblAlumnos);
        if (tblAlumnos.getColumnModel().getColumnCount() > 0) {
            tblAlumnos.getColumnModel().getColumn(0).setMinWidth(20);
            tblAlumnos.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblAlumnos.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btnExportarLista.setBackground(new java.awt.Color(51, 102, 255));
        btnExportarLista.setText("EXPORTAR LISTA");
        btnExportarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarListaActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exportar imagen.png"))); // NOI18N

        btnRegresarLista.setBackground(new java.awt.Color(51, 102, 255));
        btnRegresarLista.setText("REGRESAR ");
        btnRegresarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarListaActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VERDADEROO REGRESO.png"))); // NOI18N

        panelContenedorFirmaAsistencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelContenedorFirmaAsistenciaLayout = new javax.swing.GroupLayout(panelContenedorFirmaAsistencia);
        panelContenedorFirmaAsistencia.setLayout(panelContenedorFirmaAsistenciaLayout);
        panelContenedorFirmaAsistenciaLayout.setHorizontalGroup(
            panelContenedorFirmaAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );
        panelContenedorFirmaAsistenciaLayout.setVerticalGroup(
            panelContenedorFirmaAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        btnBorrarFirmaAsis.setBackground(new java.awt.Color(51, 102, 255));
        btnBorrarFirmaAsis.setText("Borrar Firma");
        btnBorrarFirmaAsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarFirmaAsisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRegresarLista)
                                .addGap(104, 104, 104))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panelContenedorFirmaAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBorrarFirmaAsis)
                                .addGap(99, 99, 99)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnExportarLista)
                                .addGap(115, 115, 115))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(157, 157, 157))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExportarLista)
                            .addComponent(btnRegresarLista)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panelContenedorFirmaAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrarFirmaAsis)))
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 770, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAlumnosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblAlumnosAncestorAdded

    }//GEN-LAST:event_tblAlumnosAncestorAdded

    private void btnExportarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarListaActionPerformed

        try { 
          MODULOSTAREAMODELAMIENTO.CConexion objetoConexion = new MODULOSTAREAMODELAMIENTO.CConexion();
          java.sql.Connection cn = objetoConexion.establecerConexion();
          // Recorremos la tabla fila por fila 
          for (int i=0;i<tblAlumnos.getRowCount();i++){
              // Obtenemos datos de las columnas
              String apellidos = tblAlumnos.getValueAt(i,1).toString();
              String nombres = tblAlumnos.getValueAt(i,2).toString();
              // Leemos el checkbox
             // 1. Leemos el valor como un objeto cualquiera
             Object valorCelda = tblAlumnos.getValueAt(i, 3);

             // 2. Verificamos: Si es nulo, es Falso. Si tiene algo, lo convertimos a boolean.
             boolean marcado = (valorCelda != null && (boolean) valorCelda);

              // 3. Ahora sí definimos el texto
               String estado = marcado ? "Presente" : "Ausente";
              
              //guardamos en la base de datos
              String sql = "INSERT INTO detalle_asistencia (id_practica,nombre_alumno,apellido_alumno,estado_asistencia)VALUES(?,?,?,?)";
              java.sql.PreparedStatement pst = cn.prepareStatement(sql);
              pst.setInt(1,idPracticaActual);
              pst.setString(2,nombres);
              pst.setString(3,apellidos);
              pst.setString(4,estado);
              
              pst.executeUpdate();   
          }
          javax.swing.JOptionPane.showMessageDialog(this,"Lista exportada correctamente.");
          //abrir el reporte final 
          Reporte_Alumnos ventanaReporte= new Reporte_Alumnos();
          ventanaReporte.cargarDatosReporte(idPracticaActual);
          // 1. Obtenemos la imagen del lienzo
          java.awt.Image fotoFirma = lienzoFirma.obtenerImagenFirma();

        // 2. Se la pasamos al reporte usando el método nuevo que creamos
           if (fotoFirma != null) {
            ventanaReporte.setFirmaDocente(fotoFirma);
           }

          ventanaReporte.setVisible(true);
          this.dispose();
          ventanaReporte.setVisible(true);
          this.dispose();
      }catch (Exception e){
          javax.swing.JOptionPane.showMessageDialog(this,"Error al exportar: "+ e);
          
      }
        
       
    }//GEN-LAST:event_btnExportarListaActionPerformed

    private void btnRegresarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarListaActionPerformed
        REGISTRAR_PRACTICA newframe= new REGISTRAR_PRACTICA();
      newframe.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnRegresarListaActionPerformed

    private void btnBorrarFirmaAsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarFirmaAsisActionPerformed
       
    if (lienzoFirma != null) {
        lienzoFirma.limpiarCanvas();
    }
    }//GEN-LAST:event_btnBorrarFirmaAsisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asistencia_de_Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asistencia_de_Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asistencia_de_Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asistencia_de_Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asistencia_de_Alumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarFirmaAsis;
    private javax.swing.JButton btnExportarLista;
    private javax.swing.JButton btnRegresarLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelContenedorFirmaAsistencia;
    private javax.swing.JTable tblAlumnos;
    // End of variables declaration//GEN-END:variables
// --- PEGAR AL FINAL DE Asistencia_de_Alumnos.java, ANTES DE LA ÚLTIMA LLAVE } ---
    
    class PanelLienzoFirma extends javax.swing.JPanel {
        // Hacemos la imagen accesible
        public java.awt.image.BufferedImage imagenFirma;
        private java.awt.Graphics2D g2d;
        private int Xantiguo, Yantiguo, Xnuevo, Ynuevo;

        public PanelLienzoFirma() {
            this.setBackground(java.awt.Color.WHITE);
            this.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
            
            this.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override public void mousePressed(java.awt.event.MouseEvent e) {
                    Xantiguo = e.getX(); Yantiguo = e.getY();
                }
            });
            this.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                @Override public void mouseDragged(java.awt.event.MouseEvent e) {
                    Xnuevo = e.getX(); Ynuevo = e.getY();
                    if (g2d != null) {
                        g2d.drawLine(Xantiguo, Yantiguo, Xnuevo, Ynuevo);
                        Xantiguo = Xnuevo; Yantiguo = Ynuevo;
                        repaint();
                    }
                }
            });
        }

        @Override protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);
            if (imagenFirma == null) {
                 // Crear imagen del tamaño exacto del panel
                imagenFirma = new java.awt.image.BufferedImage(getWidth(), getHeight(), java.awt.image.BufferedImage.TYPE_INT_RGB);
                g2d = imagenFirma.createGraphics();
                g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                // Rellenar de blanco inicialmente
                g2d.setColor(java.awt.Color.WHITE);
                g2d.fillRect(0, 0, getWidth(), getHeight());
                // Configurar pincel negro
                g2d.setColor(java.awt.Color.BLACK);
                g2d.setStroke(new java.awt.BasicStroke(2f));
            }
            g.drawImage(imagenFirma, 0, 0, null);
        }
        
        public void limpiarCanvas() {
            if (g2d != null) {
                g2d.setColor(java.awt.Color.WHITE);
                g2d.fillRect(0, 0, getWidth(), getHeight());
                g2d.setColor(java.awt.Color.BLACK);
                repaint();
            }
        }
        
        // MÉTODO NUEVO IMPORTANTE: Para sacar la "foto" de la firma
        public java.awt.Image obtenerImagenFirma() {
            return this.imagenFirma;
        }
    }
}
