/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ALEX
 */
public class MODULO_ROL extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MODULO_ROL.class.getName());

    /**
     * Creates new form MODULO_ROL
     */
    public MODULO_ROL() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TXTIMAGEN2 = new javax.swing.JLabel();
        BTNREPORTE = new javax.swing.JButton();
        TXTIMAGEN = new javax.swing.JLabel();
        btnGestionarCursos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BTNGESTIONARLABORATORIO1 = new javax.swing.JButton();
        BTNREGRESAR = new javax.swing.JButton();
        TXTFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MÓDULO DE ADMINISTRADOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        TXTIMAGEN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/33.png"))); // NOI18N
        getContentPane().add(TXTIMAGEN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 120, 170));

        BTNREPORTE.setBackground(new java.awt.Color(51, 204, 255));
        BTNREPORTE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTNREPORTE.setForeground(new java.awt.Color(255, 255, 255));
        BTNREPORTE.setText("REALIZAR REPORTE");
        BTNREPORTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREPORTEActionPerformed(evt);
            }
        });
        getContentPane().add(BTNREPORTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 170, 40));

        TXTIMAGEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/444.png"))); // NOI18N
        getContentPane().add(TXTIMAGEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 130, 130));

        btnGestionarCursos.setBackground(new java.awt.Color(51, 204, 255));
        btnGestionarCursos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGestionarCursos.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarCursos.setText("ASIGNAR CURSOS");
        btnGestionarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarCursosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGestionarCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 210, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administracion (3).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));

        BTNGESTIONARLABORATORIO1.setBackground(new java.awt.Color(51, 204, 255));
        BTNGESTIONARLABORATORIO1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTNGESTIONARLABORATORIO1.setForeground(new java.awt.Color(255, 255, 255));
        BTNGESTIONARLABORATORIO1.setText("GESTIONAR DOCENTE");
        BTNGESTIONARLABORATORIO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGESTIONARLABORATORIO1ActionPerformed(evt);
            }
        });
        getContentPane().add(BTNGESTIONARLABORATORIO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 210, 40));

        BTNREGRESAR.setBackground(new java.awt.Color(51, 204, 255));
        BTNREGRESAR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTNREGRESAR.setForeground(new java.awt.Color(255, 255, 255));
        BTNREGRESAR.setText("REGRESAR");
        BTNREGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREGRESARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNREGRESAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 30));

        TXTFONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo.png"))); // NOI18N
        getContentPane().add(TXTFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNREPORTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREPORTEActionPerformed
    //redirije a la pestaña o panel de modulo
    MODULO newframe= new MODULO();
    
    newframe.setVisible(true);
    
    
    this.dispose();
    }//GEN-LAST:event_BTNREPORTEActionPerformed

    private void BTNGESTIONARLABORATORIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGESTIONARLABORATORIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNGESTIONARLABORATORIOActionPerformed

    private void btnGestionarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarCursosActionPerformed
       GestionarCurso newframe= new GestionarCurso();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionarCursosActionPerformed

    private void BTNGESTIONARLABORATORIO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGESTIONARLABORATORIO1ActionPerformed
       
         RegistrarDocente login=new RegistrarDocente();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNGESTIONARLABORATORIO1ActionPerformed

    private void BTNREGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREGRESARActionPerformed
       inicio login=new inicio();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNREGRESARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MODULO_ROL().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNGESTIONARLABORATORIO1;
    private javax.swing.JButton BTNREGRESAR;
    private javax.swing.JButton BTNREPORTE;
    private javax.swing.JLabel TXTFONDO;
    private javax.swing.JLabel TXTIMAGEN;
    private javax.swing.JLabel TXTIMAGEN2;
    private javax.swing.JButton btnGestionarCursos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
