/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ALEX
 */
public class MODULO_ROL extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MODULO_ROL.class.getName());

    /**
     * Creates new form MODULO_ROL
     */
    public MODULO_ROL() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TXTIMAGEN2 = new javax.swing.JLabel();
        BTNREPORTE = new javax.swing.JButton();
        TXTIMAGEN = new javax.swing.JLabel();
        BTNREPORTE1 = new javax.swing.JButton();
        BTNGESTIONARLABORATORIO = new javax.swing.JButton();
        TXTFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MÓDULO DE ADMINISTRADOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        TXTIMAGEN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/33.png"))); // NOI18N
        getContentPane().add(TXTIMAGEN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 120, 170));

        BTNREPORTE.setBackground(new java.awt.Color(51, 204, 255));
        BTNREPORTE.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BTNREPORTE.setForeground(new java.awt.Color(255, 255, 255));
        BTNREPORTE.setText("REALIZAR REPORTE");
        BTNREPORTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREPORTEActionPerformed(evt);
            }
        });
        getContentPane().add(BTNREPORTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 250, 50));

        TXTIMAGEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/444.png"))); // NOI18N
        getContentPane().add(TXTIMAGEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 140, 130));

        BTNREPORTE1.setBackground(new java.awt.Color(51, 204, 255));
        BTNREPORTE1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BTNREPORTE1.setForeground(new java.awt.Color(255, 255, 255));
        BTNREPORTE1.setText("REALIZAR REPORTE");
        getContentPane().add(BTNREPORTE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 250, 50));

        BTNGESTIONARLABORATORIO.setBackground(new java.awt.Color(51, 204, 255));
        BTNGESTIONARLABORATORIO.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BTNGESTIONARLABORATORIO.setForeground(new java.awt.Color(255, 255, 255));
        BTNGESTIONARLABORATORIO.setText("GESTIONAR LABORATORIO");
        BTNGESTIONARLABORATORIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGESTIONARLABORATORIOActionPerformed(evt);
            }
        });
        getContentPane().add(BTNGESTIONARLABORATORIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 350, 50));

        TXTFONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/606b54b09207dc84eeed2ee6_background.jpeg"))); // NOI18N
        getContentPane().add(TXTFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 511));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNREPORTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREPORTEActionPerformed
    //redirije a la pestaña o panel de modulo
    MODULO newframe= new MODULO();
    
    newframe.setVisible(true);
    
    //paraevitar que aparezcan dobles pestañas
    
    this.dispose();
    }//GEN-LAST:event_BTNREPORTEActionPerformed

    private void BTNGESTIONARLABORATORIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGESTIONARLABORATORIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNGESTIONARLABORATORIOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MODULO_ROL().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNGESTIONARLABORATORIO;
    private javax.swing.JButton BTNREPORTE;
    private javax.swing.JButton BTNREPORTE1;
    private javax.swing.JLabel TXTFONDO;
    private javax.swing.JLabel TXTIMAGEN;
    private javax.swing.JLabel TXTIMAGEN2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
