
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ALEX
 */
public class MODULO extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MODULO.class.getName());

    /**
     * Creates new form MODULO
     */
    public MODULO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXTMODULO = new javax.swing.JLabel();
        TXTLABORATORIO = new javax.swing.JLabel();
        TXTFACULTAD = new javax.swing.JLabel();
        txtcurso = new javax.swing.JLabel();
        CURSO = new javax.swing.JComboBox<>();
        FACULTAD = new javax.swing.JComboBox<>();
        LABORATORIO = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TXTFECHA = new javax.swing.JTextField();
        TXTHORAINICIO = new javax.swing.JLabel();
        TXTHORAFIN = new javax.swing.JLabel();
        txthorainicio = new javax.swing.JTextField();
        txthorafin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TXTDOCENTE = new javax.swing.JTextField();
        BTNREGRESAR = new javax.swing.JButton();
        TXTFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TXTMODULO.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TXTMODULO.setForeground(new java.awt.Color(255, 255, 255));
        TXTMODULO.setText("MÓDULO DE REPORTE");
        getContentPane().add(TXTMODULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        TXTLABORATORIO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTLABORATORIO.setForeground(new java.awt.Color(255, 255, 255));
        TXTLABORATORIO.setText("SELECCIONE LABORATORIO");
        getContentPane().add(TXTLABORATORIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        TXTFACULTAD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTFACULTAD.setForeground(new java.awt.Color(255, 255, 255));
        TXTFACULTAD.setText("SELECCIONE FACULTAD");
        getContentPane().add(TXTFACULTAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        txtcurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcurso.setForeground(new java.awt.Color(255, 255, 255));
        txtcurso.setText("SELECCIONE CURSO");
        getContentPane().add(txtcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, -1));

        CURSO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ㅤㅤㅤ", "Taller programación", "Modelamiento de datos", "Estadistica Aplicada" }));
        CURSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CURSOActionPerformed(evt);
            }
        });
        getContentPane().add(CURSO, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 210, 30));

        FACULTAD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ㅤㅤㅤ", "INGENIERIA DE SISTEMAS", "INDUSTRIAL", "INGENIERIA CIVIL", "DERECHO" }));
        FACULTAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FACULTADActionPerformed(evt);
            }
        });
        getContentPane().add(FACULTAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 230, 30));

        LABORATORIO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ㅤㅤㅤ", "402-D", "202-D", "305-D", "602-D" }));
        LABORATORIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LABORATORIOActionPerformed(evt);
            }
        });
        getContentPane().add(LABORATORIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 220, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FECHA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        TXTFECHA.setBackground(new java.awt.Color(255, 255, 255));
        TXTFECHA.setForeground(new java.awt.Color(0, 0, 0));
        TXTFECHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTFECHAActionPerformed(evt);
            }
        });
        getContentPane().add(TXTFECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 130, 30));

        TXTHORAINICIO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTHORAINICIO.setForeground(new java.awt.Color(255, 255, 255));
        TXTHORAINICIO.setText("HORA INICIO");
        getContentPane().add(TXTHORAINICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        TXTHORAFIN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTHORAFIN.setForeground(new java.awt.Color(255, 255, 255));
        TXTHORAFIN.setText("HORA FIN");
        getContentPane().add(TXTHORAFIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        txthorainicio.setBackground(new java.awt.Color(255, 255, 255));
        txthorainicio.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txthorainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 110, 30));

        txthorafin.setBackground(new java.awt.Color(255, 255, 255));
        txthorafin.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txthorafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 100, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DOCENTE A CARGO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, -1, -1));

        TXTDOCENTE.setBackground(new java.awt.Color(255, 255, 255));
        TXTDOCENTE.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TXTDOCENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 270, 30));

        BTNREGRESAR.setBackground(new java.awt.Color(51, 204, 255));
        BTNREGRESAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BTNREGRESAR.setForeground(new java.awt.Color(255, 255, 255));
        BTNREGRESAR.setText("REGRESAR");
        BTNREGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREGRESARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNREGRESAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, -1, -1));

        TXTFONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/606b54b09207dc84eeed2ee6_background.jpeg"))); // NOI18N
        TXTFONDO.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TXTFONDOAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(TXTFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTFONDOAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TXTFONDOAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFONDOAncestorAdded

    private void CURSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CURSOActionPerformed
        String mensaje= null;
        mensaje = CURSO.getSelectedItem().toString();
        
    }//GEN-LAST:event_CURSOActionPerformed

    private void FACULTADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FACULTADActionPerformed
        String mensaje= null;
        mensaje = FACULTAD.getSelectedItem().toString();
    }//GEN-LAST:event_FACULTADActionPerformed

    private void LABORATORIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LABORATORIOActionPerformed
        String mensaje= null;
        mensaje = LABORATORIO.getSelectedItem().toString();
    }//GEN-LAST:event_LABORATORIOActionPerformed

    private void TXTFECHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTFECHAActionPerformed
        
    }//GEN-LAST:event_TXTFECHAActionPerformed

    
    //boton regresar
    
    private void BTNREGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREGRESARActionPerformed
    //permite que el boton regresar, regrese a modulo de roles
    MODULO_ROL newframe= new MODULO_ROL();
    
    newframe.setVisible(true);
        //this evita que las ventanas se acumulen
    this.dispose();   
     //this evitar que las ventanas se acumulen   
        
    }//GEN-LAST:event_BTNREGRESARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MODULO().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNREGRESAR;
    private javax.swing.JComboBox<String> CURSO;
    private javax.swing.JComboBox<String> FACULTAD;
    private javax.swing.JComboBox<String> LABORATORIO;
    private javax.swing.JTextField TXTDOCENTE;
    private javax.swing.JLabel TXTFACULTAD;
    private javax.swing.JTextField TXTFECHA;
    private javax.swing.JLabel TXTFONDO;
    private javax.swing.JLabel TXTHORAFIN;
    private javax.swing.JLabel TXTHORAINICIO;
    private javax.swing.JLabel TXTLABORATORIO;
    private javax.swing.JLabel TXTMODULO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtcurso;
    private javax.swing.JTextField txthorafin;
    private javax.swing.JTextField txthorainicio;
    // End of variables declaration//GEN-END:variables
}
