import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
public class REGISTRAR_PRACTICA extends javax.swing.JFrame {

    /**
     * Creates new form REGISTRAR_PRACTICA
     */
    public REGISTRAR_PRACTICA() {
        initComponents();
     setLocationRelativeTo(null);
        // 1. FECHA
        LocalDate fechaHoy = LocalDate.now();
        DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        // IMPORTANTE: Asegúrate que tu caja de texto de fecha se llame txtFecha
        txtFecha.setText(fechaHoy.format(formatoFecha));
        
        // 2. HORA INICIO
        LocalTime horaActual = LocalTime.now();
        DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm");
        // Asegúrate que tu caja de hora inicio se llame txtHoraInicio
        txtHoraInicio.setText(horaActual.format(formatoHora));
        
        // 3. HORA FIN (Calculamos 2 horas más tarde)
        LocalTime horaSalida = horaActual.plusHours(2); 
        // Asegúrate que tu caja de hora fin se llame txtHoraFin
        txtHoraFin.setText(horaSalida.format(formatoHora));
        // ... (Tu código de fecha y hora está arriba) ...

        // --- CÓDIGO PARA JALAR EL NOMBRE DESDE LA BASE DE DATOS ---
        try {
            // 1. Obtenemos el usuario que inició sesión (ej: "martin")
            String usuarioLogueado = MODULOSTAREAMODELAMIENTO.Sesion.usuarioActual;
            
            // 2. Conectamos a la base de datos
            MODULOSTAREAMODELAMIENTO.CConexion objetoConexion = new MODULOSTAREAMODELAMIENTO.CConexion();
            java.sql.Connection cn = objetoConexion.establecerConexion();
            
            // 3. Hacemos la consulta: "¿Cuál es el nombre_completo de este usuario?"
            String sql = "SELECT nombre_completo FROM usuarios WHERE usuario = ?";
            java.sql.PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, usuarioLogueado);
            
            java.sql.ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                // 4. SI LO ENCONTRAMOS: Jalamos el dato de la columna "nombre_completo"
                String nombreReal = rs.getString("nombre_completo");
                
                // 5. Lo ponemos en la caja de texto (Asegúrate que se llame txtDocente)
                txtDocente.setText(nombreReal);
                
                // (Opcional) Bloqueamos la caja para que no se pueda editar
                txtDocente.setEditable(false);
            }
            
        } catch (Exception e) {
            System.out.println("Error al jalar el docente de la BD: " + e);
        }
        // --- CÓDIGO PARA CARGAR LOS CURSOS DEL DOCENTE ---
        try {
            // 1. Limpiamos la lista para que no tenga basura
            cboCurso.removeAllItems();
            cboCurso.addItem("Seleccione un curso"); 
            
            // 2. Recuperamos el usuario que está conectado (ej: "martin")
            String usuarioLogueado = MODULOSTAREAMODELAMIENTO.Sesion.usuarioActual;
            
            // 3. Conectamos a la base de datos
            MODULOSTAREAMODELAMIENTO.CConexion objetoConexion = new MODULOSTAREAMODELAMIENTO.CConexion();
            java.sql.Connection cn = objetoConexion.establecerConexion();
            
            // 4. Buscamos SOLO los cursos que le pertenecen a este usuario
            String sql = "SELECT nombre_curso FROM cursos_docente WHERE usuario_docente = ?";
            java.sql.PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, usuarioLogueado);
            
            java.sql.ResultSet rs = pst.executeQuery();
            
            // 5. Llenamos la lista con los resultados
            while (rs.next()) {
                cboCurso.addItem(rs.getString("nombre_curso"));
            }
            
        } catch (Exception e) {
            System.out.println("Error al cargar cursos: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        txtfondo2 = new javax.swing.JPanel();
        txtFacultad = new javax.swing.JLabel();
        cajaFacultad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtDocente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTituloPractica = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CajaProgramaAcademico = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CajaCiclo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CajaSeccion = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        CajaPractica = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JTextField();
        txtHoraFin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cajaLaboratorios = new javax.swing.JComboBox<>();
        txtRegresar = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cboCurso = new javax.swing.JComboBox<>();
        txtFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_uai123456789.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 170, 60));

        txtfondo2.setBackground(new java.awt.Color(0,0,0,100));
        txtfondo2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FICHA DE ASISTENCIA DE PRACTICAS DE LABORATORIO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Swis721 Lt BT", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        txtFacultad.setForeground(new java.awt.Color(255, 255, 255));
        txtFacultad.setText("FACULTAD:");

        cajaFacultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Facultad", "FICA (Facultad de Ingenieria, Ciencias y Administración)", "FCS (Facultad de Ciencias de la Salud)" }));
        cajaFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaFacultadActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DOCENTE:");

        txtDocente.setEnabled(false);
        txtDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocenteActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TITULO DE LA PRÁCTICA:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PROGRAMA ACADEMICO:");

        CajaProgramaAcademico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingenieria de Sistemas" }));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FECHA DE PRACTICA:");

        txtFecha.setEnabled(false);
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CICLO:");

        CajaCiclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Ciclo", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X" }));
        CajaCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaCicloActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CURSO:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SECCIÓN:");

        CajaSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Sección", "A", "B", "C", "D", "E" }));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("N° PRACTICA:");

        CajaPractica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el N°", "N°1", "N°2", "N°3", "N°4", "N°5", "N°6", "N°7", "N°8", "N°9", "N°10", "N°11", "N°12", "N°13", "N°14", "N°15", "N°16" }));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HORA INICIO:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("HORA FIN:");

        txtHoraInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraInicioActionPerformed(evt);
            }
        });

        txtHoraFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraFinActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("LABORATORIO O TALLER SOLICITADO:");

        cajaLaboratorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Laboratorio", "Sala de Audiencias-(203-D)", "Automatización-(201-B)", "Laboratorio de Fisica-(204-A)", "Resistencia de Materiales-(103-D)", "Design Thinking-(202-D)", "Psicometrico 1-(203-B)", "Psicometrico 2-(302-D)", "Laboratorio de Computo 1-(206-A)", "Laboratorio de Computo 2-(205-A)", "Laboratorio de Computo 3-(202-A)", "Laboratorio de Computo 4-(201-D)", "Laboratorio de Computo 5-(301-D)", "Camara Gesell-(202-B)", "Microbiologia-Medicina-(106-A)", "Enfermeria Basica- (103-B)", "Enfermeria Especializada 1-(101-B)", "Enfermeria Especializada 2 -(102-B)", "Taller Topografia (306-C)", "Quimica y Bioquimica-(104-B)", "Biologia y Microbiologia- (105-B)", "Anatomia-(204-B)", "Consultoria Sexual y Reproductiva-(202-C)", "Obstetricia y Humanistico- (205-D)", "Dibujo-(301 y 302-D)", "Laboratorio de Redes-(201-C)", "Laboratorio de Operaciones Unitarias-(101-D)" }));

        txtRegresar.setBackground(new java.awt.Color(51, 102, 255));
        txtRegresar.setForeground(new java.awt.Color(255, 255, 255));
        txtRegresar.setText("REGRESAR");
        txtRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegresarActionPerformed(evt);
            }
        });

        btnGuardarCambios.setBackground(new java.awt.Color(51, 102, 255));
        btnGuardarCambios.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarCambios.setText("GUARDAR CAMBIOS");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VERDADEROO REGRESO.png"))); // NOI18N

        javax.swing.GroupLayout txtfondo2Layout = new javax.swing.GroupLayout(txtfondo2);
        txtfondo2.setLayout(txtfondo2Layout);
        txtfondo2Layout.setHorizontalGroup(
            txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtfondo2Layout.createSequentialGroup()
                .addGroup(txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtfondo2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtfondo2Layout.createSequentialGroup()
                                .addComponent(txtFacultad)
                                .addGap(15, 15, 15)
                                .addComponent(cajaFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(txtfondo2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(txtfondo2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CajaProgramaAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(txtfondo2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtfondo2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(txtfondo2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTituloPractica, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtfondo2Layout.createSequentialGroup()
                        .addGroup(txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CajaCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(txtfondo2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CajaSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(txtfondo2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CajaPractica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(txtfondo2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(txtfondo2Layout.createSequentialGroup()
                .addGroup(txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtfondo2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaLaboratorios, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(txtfondo2Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(txtfondo2Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)
                        .addComponent(btnGuardarCambios)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        txtfondo2Layout.setVerticalGroup(
            txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtfondo2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFacultad)
                    .addComponent(cajaFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(CajaCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CajaProgramaAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(CajaSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTituloPractica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(CajaPractica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cajaLaboratorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGroup(txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtfondo2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(txtfondo2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(txtfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegresar)
                            .addComponent(btnGuardarCambios))))
                .addGap(118, 118, 118))
        );

        getContentPane().add(txtfondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 830, 430));

        txtFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo.png"))); // NOI18N
        getContentPane().add(txtFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaFacultadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaFacultadActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtHoraInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraInicioActionPerformed

    private void txtHoraFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraFinActionPerformed

    private void txtRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegresarActionPerformed
         inicio ROLES=new inicio();
        ROLES.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtRegresarActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed

    // --- 1. RECOLECTAR DATOS DEL FORMULARIO ---
    String facultad = cajaFacultad.getSelectedItem().toString();
    // Asegúrate de usar el nombre correcto de tu combo (cboCurso o cmbCurso)
    String curso = cboCurso.getSelectedItem().toString(); 
    String docente = txtDocente.getText();
    String tema = txtTituloPractica.getText(); 
    String fecha = txtFecha.getText();
    String horaIn = txtHoraInicio.getText();
    String horaFin = txtHoraFin.getText();
    String ProgramaAcademico = CajaProgramaAcademico.getSelectedItem().toString();
    String Laboratorios = cajaLaboratorios.getSelectedItem().toString();
    String Ciclo = CajaCiclo.getSelectedItem().toString();
    String Seccion = CajaSeccion.getSelectedItem().toString();
    String NumeroPractica = CajaPractica.getSelectedItem().toString();

    // --- 2. GUARDAR EN BASE DE DATOS ---
    try {
        MODULOSTAREAMODELAMIENTO.CConexion objetoConexion = new MODULOSTAREAMODELAMIENTO.CConexion();
        java.sql.Connection cn = objetoConexion.establecerConexion();

        String sql = "INSERT INTO practicas_laboratorio "
                + "(facultad, curso, docente, titulo_practica, fecha, hora_inicio, hora_fin, programa, laboratorio, ciclo, seccion, num_practica) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
        // Preparamos para recibir el ID generado automáticamente
        java.sql.PreparedStatement pst = cn.prepareStatement(sql, java.sql.Statement.RETURN_GENERATED_KEYS);
        
        pst.setString(1, facultad);
        pst.setString(2, curso);
        pst.setString(3, docente);
        pst.setString(4, tema);
        pst.setString(5, fecha);
        pst.setString(6, horaIn);
        pst.setString(7, horaFin);
        pst.setString(8, ProgramaAcademico);
        pst.setString(9, Laboratorios);
        pst.setString(10, Ciclo);
        pst.setString(11, Seccion);
        pst.setString(12, NumeroPractica);
        
        int filasAfectadas = pst.executeUpdate(); 

        // --- 3. SI SE GUARDÓ, ABRIMOS LA VENTANA (UNA SOLA VEZ) ---
        if (filasAfectadas > 0) {
            java.sql.ResultSet rs = pst.getGeneratedKeys();
            
            if (rs.next()) {
                int idGenerado = rs.getInt(1); // Capturamos el ID
                
                javax.swing.JOptionPane.showMessageDialog(this, "Datos guardados correctamente.");

                // Creamos la instancia de la siguiente ventana
                Asistencia_de_Alumnos ventanaSiguiente = new Asistencia_de_Alumnos();
                
                // LE PASAMOS TODO LO NECESARIO:
                
                // A) El ID para guardar la asistencia después
                ventanaSiguiente.setIdPractica(idGenerado); 
                
                // B) El Curso para que cargue la lista VISUALMENTE
                ventanaSiguiente.cargarAlumnosPorCurso(curso); 
                
                // C) OPCIONAL: Si necesitas pasar datos de cabecera para el reporte final,
                // puedes guardarlos en variables globales de ventanaSiguiente aquí mismo.
                // Ejemplo: ventanaSiguiente.g_docente = docente;
                
                // Mostramos la ventana UNICA y cerramos esta
                ventanaSiguiente.setVisible(true);
                this.dispose();
            }
        }
        cn.close();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar: " + e);
    }

    }//GEN-LAST:event_btnGuardarCambiosActionPerformed


    private void txtDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocenteActionPerformed

    private void CajaCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaCicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaCicloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTRAR_PRACTICA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTRAR_PRACTICA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTRAR_PRACTICA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTRAR_PRACTICA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTRAR_PRACTICA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CajaCiclo;
    private javax.swing.JComboBox<String> CajaPractica;
    private javax.swing.JComboBox<String> CajaProgramaAcademico;
    private javax.swing.JComboBox<String> CajaSeccion;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JComboBox<String> cajaFacultad;
    private javax.swing.JComboBox<String> cajaLaboratorios;
    private javax.swing.JComboBox<String> cboCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDocente;
    private javax.swing.JLabel txtFacultad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JLabel txtFondo;
    private javax.swing.JTextField txtHoraFin;
    private javax.swing.JTextField txtHoraInicio;
    private javax.swing.JButton txtRegresar;
    private javax.swing.JTextField txtTituloPractica;
    private javax.swing.JPanel txtfondo2;
    // End of variables declaration//GEN-END:variables
}
